### ISSUE TITLE
Optimal bpp palette generation should pad the resulting palette

### ISSUE THREAD

**Issue by eiowlta** [espruino/EspruinoWebTools#8]
The palette generation should pad the palette in the event the image contains fewer colors than the palette size.

I have an image with 3 colors (yellow, red and "transparent").  Using Optimal 2 bit, it produces 
{
  width : 16, height : 9, bpp : 2,
  transparent : 0,
  palette : new Uint16Array([65535,63488,65504]),
  buffer : atob("AEABAAAQBABAEAQBEAAABAQmZBAAmZkAAmZmQAmZmZAGZmZg")
}

When using this on my Bangle.js 2, the graphics library says that it expects a power of 2 size for the palette.  
If I use the Image String option, the library interprets the first few pixels as a color and the image is shifted.  

I can send in a PR when I'm at my main dev machine.

**Comment by gfwilliams** [comment]
Good spot - thanks! A PR would be great

**Comment by gfwilliams** [comment]
Fixed with https://github.com/espruino/EspruinoWebTools/pull/9
